config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get '' => 'books#top'
    get 'books' => 'books#index'
    post 'books' => 'books#create'
    get 'books/:id' => 'books#show'
    get 'books/:id/edit' => 'books#edit' ,as: 'edit_e'
    patch 'books/:id/edit' => 'books#update', as: 'update_up'
    delete 'books/:id' => 'books#destroy', as: 'destroy_d'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,presence:true
    validates :body,presence:true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def top
    end
    
    def index
        @books = Book.all
        @book = Book.new
    end 
    def create
        @book = Book.new(book_params)
        if @book.save
            flash[:notice] = "Book was successfully created."
            redirect_to "/books/#{@book.id}" 
        else
            @books = Book.all
            render :index
        end
    end
    
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        flash[:notice] = "Book was successfully destroyed."
        redirect_to "/books"
    end 
    
    def show
        @data = Book.find(params[:id])
       
    end 
    
    def edit
         @edit = Book.find(params[:id])
        
    end 
    
    def update
        if @edit = Book.find(params[:id])
            @edit.update(book_params)
            flash[:notice] = "Book was successfully updated."
            redirect_to "/books/#{@edit.id}"
        end 
    end 
    
    
    private
    def book_params
        params.require(:book).permit(:title, :body)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="edit-box">
    <h1 class="edit">Editing Book</h1>

        <div class="edit-title-box">
            <%= form_with model: @edit, url: update_up_path(@edit.id), method: :patch do |f| %>
            <label class="edit-title">Title</label>
              <div class="text-area"><%= f.text_field :title %></div>
            <label class="edit-title">Body</label>
              <div class="text-area"><%= f.text_area :body %></div>
        
            <div class="edit-update"><%= f.submit 'Update Book' %></div>
        </div>
    
    <div class="edit-botan">
        <p class="edit-botan-text"><%= link_to "Show", "/books/#{@edit.id}" %></p>
        <p class="edit-botan-text">|</p>
        <p class="edit-botan-text"><%= link_to "Back", "/books" %></p>
    </div>
        

    <% end %>
</div>

app/views/books/index.html.erb
     <p id="notice"><%= flash[:notice] %></p>

    <h2 class="index">Books</h2>

    <table class="table">
      <thead>
        <tr>
          <th class="table-top">Title</th>
          <th class="table-top">Body</th>
          <th colspan="3"></th>
        </tr>
      </thead> 
      
      <tboody>
       
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", "/books/#{book.id}" %></td>
          <td><%= link_to "Edit", edit_e_path(book.id) %></td>
          <td><%= link_to "Destroy", destroy_d_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
        <% end %>
        </tr>
      </tboody>

    </table>

    <h3>New book</h3>
     
        <% if @book.errors.any? %>
       <div class="book">
          <p class="errors"><%= @book.errors.count %> erros prohibited this book from being saved:</p>
          <ul>
              <% @book.errors.full_messages.each do |message| %> <!--each文で<%=%>の＝を付けてしまうと全部のエラーを表示させてしまうので注意-->
              <li><%= message %></li>
              <% end %>
          </ul>
        <% end %>
      </div>

    <%= form_with model: @book do |f| %>
      
        <div class="newbook">
          <div class="field_with_errors">
            <div class="newbook-title">Title</div>
          </div>
          
          <div class="field_with_errors">
            <div><%= f.text_field :title %></div>
          </div>
        </div>
        
        <div class="newbook">
           <div class="field_with_errors">
            <div class="newbook-title">Body</div>
           </div>
          
          <div class="field_with_errors">
            <div><%= f.text_area :body %></div>
          </div>
        </div>
    
        <%= f.submit ' Create Book ' %>

    <% end %>

app/views/books/show.html.erb
<body>
<div class="show-box">
    <p id="notice"><%= flash[:notice] %></p>
    <div class=show><b>Title: </b><%= @data.title %></div>


    <div class="show"><b>Body: </b><%= @data.body %> </div>


</div>
    <div class="show-botan">
      <p class="show-text"><%= link_to "Edit", edit_e_path(@data.id) %></p>
      <p class="show-text">|</p>
      <p class="show-text"><%= link_to "Back", "/books" %></p>
    </div>
</body>

app/views/books/top.html.erb
<body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>

    <P class="top-text"><strong>Bookers </strong>では、さまざまな書籍に関するあなたの意見や</p>
    <p class="top-text">印象を共有し交換することができます</P>

    <p class="top-text"><%= link_to "start", "/books" %></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>